In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
attacks = ["paper", "replay", "mask", "total"]
rgb_model = [f"0810_{attack}_rgb" for attack in attacks]

others = ["rgbp", "rgbd", "rgbdp"]
paper_models = [f"0810_paper_{model}" for model in others]
replay_models = [f"0810_replay_{model}" for model in others]
mask_models = [f"0810_mask_{model}" for model in others]
total_models = [f"0810_total_{model}" for model in others]

In [3]:
print(paper_models)
print(replay_models)
print(mask_models)
print(total_models)

['0810_paper_rgbp', '0810_paper_rgbd', '0810_paper_rgbdp']
['0810_replay_rgbp', '0810_replay_rgbd', '0810_replay_rgbdp']
['0810_mask_rgbp', '0810_mask_rgbd', '0810_mask_rgbdp']
['0810_total_rgbp', '0810_total_rgbd', '0810_total_rgbdp']

In [4]:
# directory = "0810_paper_rgb"
# directory = "0810_paper_rgbp"
# directory = "0810_paper_rgbd"
# directory = "0810_paper_rgbdp"

# directory = "0810_replay_rgb"
# directory = "0810_replay_rgbp"
# directory = "0810_replay_rgbd"
# directory = "0810_replay_rgbdp"

# directory = "0810_mask_rgb"
directory = "0810_mask_rgbp"
# directory = "0810_mask_rgbd"
# directory = "0810_mask_rgbdp"

# directory = "0810_total_rgb"
# directory = "0810_total_rgbp"
# directory = "0810_total_rgbd"
# directory = "0810_total_rgbdp"


indoor = "/mnt/nas3/yrkim/liveness_lidar_project/GC_project/bc_output/logs/" + directory + "/" + directory + "_indoor.pkl"
outdoor = "/mnt/nas3/yrkim/liveness_lidar_project/GC_project/bc_output/logs/" + directory + "/" + directory + "_outdoor.pkl"
dark = "/mnt/nas3/yrkim/liveness_lidar_project/GC_project/bc_output/logs/" + directory + "/" + directory + "_dark.pkl"

with open(indoor,"rb") as fr:
    indoor_check = pickle.load(fr)
with open(outdoor,"rb") as fr:
    outdoor_check = pickle.load(fr)
with open(dark,"rb") as fr:
    dark_check = pickle.load(fr)

In [5]:
indoor = pd.DataFrame(indoor_check)
outdoor = pd.DataFrame(outdoor_check)
dark = pd.DataFrame(dark_check)

indoor["epoch"]=[i for i in range(1,len(indoor)+1)]
outdoor["epoch"]=[i for i in range(1,len(outdoor)+1)]
dark["epoch"]=[i for i in range(1,len(dark)+1)]

paper

rgb: 
rgb+pc : 474 
rgb+depth :
rgb+depth+pc :

In [6]:
indoor.keys()

Index(['train_loss', 'test_loss', 'train_f1', 'test_f1', 'train_acc',
       'test_acc', 'epoch'],
      dtype='object')

In [7]:
outdoor.keys()

Index(['test_loss', 'test_f1', 'test_acc', 'epoch'], dtype='object')

In [8]:
dark.keys()

Index(['test_loss', 'test_f1', 'test_acc', 'epoch'], dtype='object')

In [9]:
target = indoor[(indoor["train_f1"]!=1) | (indoor["test_f1"]!=1)]
target_list = target["epoch"].tolist()
len(target_list)

500

In [10]:
t1 = indoor.sort_values(["train_f1", "test_f1", "epoch"], ascending=[False, False, False])
t1

     train_loss  test_loss  train_f1   test_f1  train_acc  test_acc  epoch
215    0.000223   0.068526  1.000000  0.991666   1.000000  0.991667    216
214    0.000164   0.067353  1.000000  0.991666   1.000000  0.991667    215
213    0.000298   0.065042  1.000000  0.991666   1.000000  0.991667    214
211    0.000227   0.038031  1.000000  0.991666   1.000000  0.991667    212
210    0.000262   0.050491  1.000000  0.991666   1.000000  0.991667    211
..          ...        ...       ...       ...        ...       ...    ...
5      0.394234   0.063966  0.833333  0.974998   0.833333  0.975000      6
3      0.394407   0.228577  0.830554  0.908327   0.830556  0.908333      4
2      0.474063   0.402407  0.813876  0.828571   0.813889  0.833333      3
1      0.538013   0.302849  0.736060  0.891659   0.736111  0.891667      2
0      0.744192   0.398895  0.596970  0.849958   0.597222  0.850000      1

[500 rows x 7 columns]

In [11]:
t2 = outdoor.sort_values(["test_f1", "epoch"], ascending=[False, False])
t2
# t2[t2["epoch"]>=437].head(10) # paper rgb + pc

     test_loss   test_f1  test_acc  epoch
34    2.729777  0.788996  0.791667     35
35    2.337622  0.783681  0.785417     36
29    1.314954  0.782967  0.785417     30
21    1.436902  0.777917  0.779167     22
24    1.167956  0.772394  0.772917     25
..         ...       ...       ...    ...
5     6.474302  0.403409  0.533333      6
8     5.018703  0.386602  0.525000      9
6     5.492172  0.382330  0.522917      7
244   7.569935  0.333333  0.500000    245
12    9.325476  0.333333  0.500000     13

[500 rows x 4 columns]

In [12]:
t3 = dark.sort_values(["test_f1", "epoch"], ascending=[False, False])
t3
# t3[t3["epoch"]>=437].head(10) # paper rgb + pc

     test_loss   test_f1  test_acc  epoch
30    1.407233  0.569778  0.572917     31
447   1.808068  0.556994  0.572917    448
202   1.812448  0.548806  0.560417    203
443   1.896183  0.548350  0.564583    444
448   1.956269  0.547077  0.568750    449
..         ...       ...       ...    ...
2     2.478142  0.333333  0.500000      3
1     5.051297  0.333333  0.500000      2
48    4.163567  0.332406  0.497917     49
0     3.152243  0.332406  0.497917      1
135   1.691693  0.329352  0.483333    136

[500 rows x 4 columns]

In [13]:
print(len(target_list))
print(len(t2))
print(len(t3))
for epoch in target_list:
    t2 = t2.drop(t2[t2["epoch"]==epoch].index, axis=0)
    t3 = t3.drop(t3[t3["epoch"]==epoch].index, axis=0)
print(len(t2))
print(len(t3))

500
500
500
0
0

In [14]:
t2 = t2.sort_values(["test_f1", "epoch"], ascending=[False, True]).head(50)
print(len(t2))
t2

0

Empty DataFrame
Columns: [test_loss, test_f1, test_acc, epoch]
Index: []

In [15]:
t3 = t3.sort_values(["test_f1", "epoch"], ascending=[False, False]).head(50)
print(len(t3))
t3

0

Empty DataFrame
Columns: [test_loss, test_f1, test_acc, epoch]
Index: []

In [16]:
print(indoor[indoor["epoch"]==6])

indoor.sort_values("train_loss", ascending=False).head(50)

   train_loss  test_loss  train_f1   test_f1  train_acc  test_acc  epoch
5    0.394234   0.063966  0.833333  0.974998   0.833333     0.975      6

     train_loss  test_loss  train_f1   test_f1  train_acc  test_acc  epoch
0      0.744192   0.398895  0.596970  0.849958   0.597222  0.850000      1
1      0.538013   0.302849  0.736060  0.891659   0.736111  0.891667      2
2      0.474063   0.402407  0.813876  0.828571   0.813889  0.833333      3
148    0.420690   0.382205  0.849995  0.808000   0.850000  0.808333    149
3      0.394407   0.228577  0.830554  0.908327   0.830556  0.908333      4
5      0.394234   0.063966  0.833333  0.974998   0.833333  0.975000      6
4      0.357793   0.569232  0.861107  0.723194   0.861111  0.741667      5
28     0.315362   0.233789  0.891659  0.908020   0.891667  0.908333     29
6      0.291448   0.084934  0.888858  0.991666   0.888889  0.991667      7
8      0.276604   0.355190  0.886103  0.839786   0.886111  0.841667      9
7      0.270332   1.340933  0.902687  0.435737   0.902778  0.550000      8
201    0.259116   0.337604  0.922222  0.907815   0.922222  0.908333    202
10     0.234330   0.316637  0.908316  0.828571   0.908333  0.833333     11
9      0.227973   0.184360  0.927776  0.924576   0.927778  0.925000     10
13     0.219814   0.327907  0.930551  0.846547   0.930556  0.850000     14
11     0.200482   0.084082  0.936107  0.974998   0.936111  0.975000     12
60     0.179279   0.315316  0.936111  0.874783   0.936111  0.875000     61
450    0.173583   2.241929  0.955554  0.728507   0.955556  0.733333    451
29     0.169608   0.166100  0.944438  0.941663   0.944444  0.941667     30
18     0.165329   0.455443  0.950000  0.824988   0.950000  0.825000     19
55     0.128404   0.161127  0.950000  0.933166   0.950000  0.933333     56
19     0.127675   0.493885  0.966666  0.805291   0.966667  0.808333     20
245    0.124211   1.429580  0.966667  0.753231   0.966667  0.766667    246
244    0.110619   5.043636  0.961110  0.333333   0.961111  0.500000    245
20     0.105043   0.427942  0.961111  0.824010   0.961111  0.825000     21
451    0.104688   1.526521  0.980554  0.576290   0.980556  0.608333    452
14     0.101356   0.786080  0.975000  0.659274   0.975000  0.691667     15
12     0.095253   0.278160  0.961110  0.907557   0.961111  0.908333     13
16     0.091099   0.523104  0.977777  0.801024   0.977778  0.808333     17
30     0.086004   0.244741  0.972221  0.907815   0.972222  0.908333     31
42     0.084483   0.662015  0.969442  0.811429   0.969444  0.816667     43
70     0.082186   0.178770  0.983333  0.908276   0.983333  0.908333     71
165    0.081420   0.542338  0.983333  0.848951   0.983333  0.850000    166
75     0.072535   0.326222  0.969444  0.899301   0.969444  0.900000     76
31     0.070283   0.429335  0.975000  0.847285   0.975000  0.850000     32
41     0.063557   0.484544  0.980555  0.766602   0.980556  0.766667     42
45     0.063439   0.297149  0.980555  0.908276   0.980556  0.908333     46
57     0.062200   0.089137  0.972221  0.983329   0.972222  0.983333     58
149    0.061543   0.520740  0.983333  0.821416   0.983333  0.825000    150
263    0.059430   0.418922  0.991667  0.882155   0.991667  0.883333    264
74     0.059424   1.255369  0.980555  0.828571   0.980556  0.833333     75
169    0.054924   1.014833  0.988889  0.725643   0.988889  0.741667    170
39     0.048883   0.382525  0.991666  0.907557   0.991667  0.908333     40
48     0.047669   0.209334  0.988889  0.924576   0.988889  0.925000     49
71     0.045359   0.251535  0.988889  0.874573   0.988889  0.875000     72
249    0.044833   1.584783  0.988889  0.828571   0.988889  0.833333    250
56     0.041898   0.197789  0.975000  0.933259   0.975000  0.933333     57
43     0.041070   0.150750  0.983333  0.949986   0.983333  0.950000     44
33     0.040210   0.403532  0.983333  0.840325   0.983333  0.841667     34
17     0.038813   0.194516  0.986111  0.924953   0.986111  0.925000     18

In [17]:
3/0

ZeroDivisionError: division by zero

In [ ]:
epoch = 248

In [ ]:
print(indoor[indoor["epoch"]==epoch]["train_acc"])
print(indoor[indoor["epoch"]==epoch]["train_f1"])

print(indoor[indoor["epoch"]==epoch]["test_acc"])
print(indoor[indoor["epoch"]==epoch]["test_f1"])

print(outdoor[outdoor["epoch"]==epoch]["test_acc"])
print(outdoor[outdoor["epoch"]==epoch]["test_f1"])

print(dark[dark["epoch"]==epoch]["test_acc"])
print(dark[dark["epoch"]==epoch]["test_f1"])